[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gold = "8Vygu4A1v3dXyMhA6U7H1jp7zKRcptU4zXto8VHtNXjJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/zds/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
